# Generated by Django 4.2.7 on 2024-05-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hobby',
            field=models.CharField(default='', max_length=255, verbose_name='Хобби'),
        ),
    ]
